sudo: required
dist: trusty
group: edge

before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
            && sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
            && sudo apt-get install debian-keyring debian-archive-keyring
            && sudo apt-key update
            && sudo apt-get update -qq
            && sudo apt-get install -qq qt5-qmake qtbase5-dev qt5-default qttools5-dev-tools libqt5serialport5-dev
            && sudo apt-get install -qq zlib1g-dev libudev-dev
            && sudo apt-get install -qq libpoppler-qt5-dev
            && echo "Qt5/poppler installed";

language: cpp

# Compiler selection
compiler:
  - gcc

install: true

# Build steps
script:
  - mkdir build/
  - cd build/
  - qmake ../src/src.pro
  - make -j2
